### ISSUE TITLE
Crash on swapping to Relearned on server

### ISSUE THREAD

**Issue by Caedis** [mustapelto/DML-Relearned#1]
Built from latest 1.12 branch clone using the included gradlew script (had to convert to unix line endings)

Crash Log: [crash-2021-04-07_07.34.35-server.txt](https://github.com/mustapelto/DML-Relearned/files/6271594/crash-2021-04-07_07.34.35-server.txt)

**Comment by Caedis** [comment]
Feel free to message me in the Omni discord

**Comment by mustapelto** [comment]
The 1.12 branch is very much a work in progress and contains new code that hasn't been fully tested yet, especially not in a dedicated server environment. This particular issue is caused by a method being called on the server, when it should only be called on the client. It's an easy fix, I'll put it on my todo list for the next commit.

**Comment by Caedis** [comment]
Awesome, thanks!
